name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Remove old container
        run: docker compose down
      - name: Remove old image
        run: docker image rm jcoupalcom-jcoupal.com
      - name: Docker Compose Build
        run: docker compose build --no-cache
      - name: Docker Compose Up
        run: docker compose up -d --force-recreate
