name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Docker build
        run: docker build -t jcoupal.com .
      - name: Docker Compose Up
        run: docker compose up -d
